# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cor_cov_cpp <- function(x, y) {
    .Call(`_numTheory_cor_cov_cpp`, x, y)
}

gcd_cpp <- function(input) {
    .Call(`_numTheory_gcd_cpp`, input)
}

mod_exp <- function(base_in, exp_in, mod_in) {
    .Call(`_numTheory_mod_exp`, base_in, exp_in, mod_in)
}

prime_sieve <- function(n_in) {
    .Call(`_numTheory_prime_sieve`, n_in)
}

normal_pdf <- function(x, mean, sd) {
    .Call(`_numTheory_normal_pdf`, x, mean, sd)
}

normal_cdf <- function(x, mean, sd) {
    .Call(`_numTheory_normal_cdf`, x, mean, sd)
}

