// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cor_cov_cpp
List cor_cov_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _numTheory_cor_cov_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cor_cov_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// gcd_cpp
long long gcd_cpp(NumericVector input);
RcppExport SEXP _numTheory_gcd_cpp(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(gcd_cpp(input));
    return rcpp_result_gen;
END_RCPP
}
// mod_exp
long long mod_exp(double base_in, double exp_in, double mod_in);
RcppExport SEXP _numTheory_mod_exp(SEXP base_inSEXP, SEXP exp_inSEXP, SEXP mod_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type base_in(base_inSEXP);
    Rcpp::traits::input_parameter< double >::type exp_in(exp_inSEXP);
    Rcpp::traits::input_parameter< double >::type mod_in(mod_inSEXP);
    rcpp_result_gen = Rcpp::wrap(mod_exp(base_in, exp_in, mod_in));
    return rcpp_result_gen;
END_RCPP
}
// prime_sieve
IntegerVector prime_sieve(double n_in);
RcppExport SEXP _numTheory_prime_sieve(SEXP n_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n_in(n_inSEXP);
    rcpp_result_gen = Rcpp::wrap(prime_sieve(n_in));
    return rcpp_result_gen;
END_RCPP
}
// normal_pdf
double normal_pdf(double x, double mean, double sd);
RcppExport SEXP _numTheory_normal_pdf(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_pdf(x, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// normal_cdf
double normal_cdf(double x, double mean, double sd);
RcppExport SEXP _numTheory_normal_cdf(SEXP xSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(normal_cdf(x, mean, sd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_numTheory_cor_cov_cpp", (DL_FUNC) &_numTheory_cor_cov_cpp, 2},
    {"_numTheory_gcd_cpp", (DL_FUNC) &_numTheory_gcd_cpp, 1},
    {"_numTheory_mod_exp", (DL_FUNC) &_numTheory_mod_exp, 3},
    {"_numTheory_prime_sieve", (DL_FUNC) &_numTheory_prime_sieve, 1},
    {"_numTheory_normal_pdf", (DL_FUNC) &_numTheory_normal_pdf, 3},
    {"_numTheory_normal_cdf", (DL_FUNC) &_numTheory_normal_cdf, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_numTheory(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
